cloud:
  aws:
    s3:
      bucket: mygreensparta # AWS S3 Bucket Name
    region:
      static: ap-northeast-2 # AWS Region
    stack:
      auto: false
    credentials:
      instanceProfile: true  # AWS CLI 에서 aws configure list 정보를 반영할지의 여부